### ISSUE TITLE
chop-statistics-api TC 추가 

### ISSUE THREAD

**Issue by ors-woon** [URL-CHOP/chop-statistics-api#37]
안녕하세요 :) 

이번에 새로(?) 들어온 장철운이라고 합니다.
만기님께 다른 작업을 받기전, GRPC 나 Chop 전반에 대한 이해가 필요할 듯하여..
코드파악을 목적으로 TC를 작성해볼까 합니다.

> JUnit5 로 되어있다는 점에서 너무너무(x100) 설레는 작업이네요 👍  

생각해둔 큰틀은 아래와 같습니다.

```
0. Integration Test (다만 DB는 mocking)
1. Unit Test (GRPC / Service / Repo 단위 )
- (의문) interceptor 나 security 같은 앞단이 없는거 같은데, 굳이 GRPC도 Test를 해야할까 ?
2. 작업이 끝나면 PR 시 Test 로직을 돌리는 plugin 도 붙여볼 예정
3. 그 외 코드 파악 
```

SpringBoot를 쓴다는 점이랑, JUnit5 를 쓴다는게 너무 행복(?)해서  재밌네요 :) ㅋㅋㅋ 
잘부탁드립니다 (_ _)

**Comment by pizzazaza** [comment]
장철운님 코드 깔끔하게 잘짜시네요 👍

**Comment by ors-woon** [comment]
#### TC 를 수정하던 중 만난 이슈

1. Junit5 를 import 하면서, 사용하지 않음 (Junit4를 쓰고 있음)

확인해보니 grpc-test 쪽에 junit4 module을 사용하고 있어서 의존성이 묶이게됨.

> exclude !!
 
exclude 후,TC를 돌려보니 `@Rule` 때문에 빌드가 안됨  (Rule 은 JUnit4 에만 있다. ) 
`grpc-test 버전을 올리면 될까?` 확인해보니, 

https://github.com/grpc/grpc-java/issues/5331

얘들이 지원을 안해줌 .. 

#### 결론

```
1. grpc Test 만 Junt4 사용
2. 그외는 전부 Junit5
```

**Comment by ors-woon** [comment]
DBUnit 도입 생각 

https://github.com/rmpestano/dbunit-rules/blob/master/junit5/src/test/java/com/github/dbunit/rules/junit5/CleanBeforeAfterIt.java
